image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore src/cli.sln
      dotnet build src/cli.sln
vscode:
  extensions:
    - muhammad-sammy.csharp